title: Slides for 2021 talks - Bérénice Batut
email: berenice.batut@gmail.com
repository: bebatut-slides/2021
twitter: bebatut
linkedin: berenicebatut
gitter: bebatut
orcid: 0000-0001-9852-1987
scholar: 9sCBSXkAAAAJ
baseurl: "/2021"